# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: ap-hongkong # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  events: # 触发器
    - timer: # 签到 # 摇京豆
        parameters:
          name: jd_bean_sign_jd_club_lottery
          cronExpression: "0 0 0,12,18 * * * *"
          enable: true
          argument: jd_bean_sign&jd_club_lottery
    - timer: # 京小超兑换奖品
        parameters:
          name: jd_blueCoin
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_blueCoin
    - timer: # 东东农场# 东东萌宠
        parameters:
          name: jd_fruit_jd_pet
          cronExpression: "0 5 6-18/6 * * * *"
          enable: true
          argument: jd_fruit&jd_pet
    - timer: # 宠汪汪喂食# 宠汪汪# 摇钱树# 京东种豆得豆
        parameters:
          name: jd_joy_feedPets_jd_joy_jd_moneyTree_jd_plantBean
          cronExpression: "0 15 */1 * * * *"
          enable: true
          argument: jd_joy_feedPets&jd_joy&jd_moneyTree&jd_plantBean
    - timer: # 宠汪汪积分兑换奖品# 宠汪汪偷好友积分与狗
        parameters:
          name: jd_joy_reward_jd_joy_steal_jd_necklace
          cronExpression: "0 0 0-16/8 * * * *"
          enable: true
          argument: jd_joy_reward&jd_joy_steal&jd_necklace
    - timer: # 京东全民开红包 # 进店领豆 # 取关京东店铺商品# 京东抽奖机
        parameters:
          name: jd_redPacket_jd_shop_jd_unsubscribe_jd_lotteryMachine
          cronExpression: "0 10 0 * * * *"
          enable: true
          argument: jd_redPacket&jd_shop&jd_unsubscribe&jd_lotteryMachine
    - timer: # 京东天天加速
        parameters:
          name: jd_speed
          cronExpression: "0 8 */3 * * * *"
          enable: true
          argument: jd_speed
    - timer: # 东东超市
        parameters:
          name: jd_superMarket
          cronExpression: "0 11 1-23/5 * * * *"
          enable: true
          argument: jd_superMarket
    - timer: # 京豆变动通知 # 京东排行榜
        parameters:
          name: jd_bean_change
          cronExpression: "0 0 10 * * * *"
          enable: true
          argument: jd_bean_change&jd_rankingList
    - timer: # 金融养猪# 天天提鹅
        parameters:
          name: jd_pigPet_jd_daily_egg_jd_dreamFactory
          cronExpression: "0 12 * * * * *"
          enable: true
          argument: jd_pigPet&jd_daily_egg&jd_dreamFactory
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
