# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  namespace: default
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: 
    src: ./
    exclude:
      - '*.!(js|txt|json)'
      - 'backUp/**'
      - 'icon/**'
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs12.16
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 64 # 内存大小，单位MB
  timeout: 3600 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  retryNum: 0
  events: #触发器
    - timer:
        parameters:
          name: config
          cronExpression: "0 0 * * * * *"
          enable: true
          argument: config
    - timer: #宠汪汪积分兑换京豆
        parameters:
          name: joyreward
          cronExpression: "0 59 7,15,23 * * * *"
          enable: true
          argument: jd_joy_reward
    - timer: #汽车兑换
        parameters:
          name: car_exchange
          cronExpression: "30 59 23 * * * *"
          enable: false
          argument: jd_car_exchange
    - timer: #超市蓝币兑换
        parameters:
          name: blueCoin
          cronExpression: "0 59 23 * * * *"
          enable: true
          argument: jd_blueCoin
  environment: #  环境变量
    variables: #  环境变量对象