# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs12.16
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 64 # 内存大小，单位MB
  timeout: 86400 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  installDependency: true # 是否在线安装依赖
  events: #触发器
    - timer: #签到 #摇京豆 #进店领豆 #京东试用
        parameters:
          name: beansign_clublottery_shop_try
          cronExpression: "0 1 0 * * * *"
          enable: true
          argument: jd_bean_sign&jd_club_lottery&jd_shop&jd_try&jd_sign
    - timer: #取关京东店铺商品 #京东抽奖机 #京东汽车 #京东秒秒币 #天天提鹅 #领金贴
        parameters:
          name: unsubscribe_lotteryMachine_car_ms_jintie
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_unsubscribe&jd_lotteryMachine&jd_car&jd_ms&jd_jin_tie&jd_get_share_code
    - timer: #东东农场 #东东萌宠 #京喜农场 #京东极速版红包 #美丽研究院
        parameters:
          name: fruit_pet_jxnc_speedsign_speedredpocke_beauty
          cronExpression: "0 5 0-18/6,8 * * * *"
          enable: true
          argument: jd_fruit&jd_pet&jd_jxnc&jd_speed_sign&jd_speed_redpocke
    - timer: #宠汪汪 #摇钱树 #京东种豆得豆 #京喜工厂 #东东工厂 #健康社区收取能量  #燃动夏季
        parameters:
          name: feedPets_moneyTree_plantBean_dreamFactory_jdfactory_healthenergy
          cronExpression: "0 3 0,6-23/1 * * * *"
          enable: true
          argument: jd_moneyTree&jd_plantBean&jd_dreamFactory&jd_jdfactory&jd_z_health_energy&jd_summer_movement
    - timer: #宠汪汪积分兑换京豆 #签到领现金 #东东小窝 #京东直播 #金榜创造营 #全民开红包
        parameters:
          name: cash_smallhome_live
          cronExpression: "0 0 0-16/8,20 * * * *"
          enable: true
          argument: jd_cash&jd_small_home&jd_live&jd_gold_creator&jd_redPacket&jd_mohe
    - timer: #健康社区 #天天提鹅 #抢京豆
        parameters:
          name: healthcommunity_dailyegg_qjd
          cronExpression: "2 36 0,6-23/4 * * * *"
          enable: true
          argument: jd_z_health_community&jd_daily_egg&jd_qjd&jd_zjb
    - timer: #东东超市 #京喜财富岛 #京喜牧场 #京享值PK
        parameters:
          name: cfd_superMarket
          cronExpression: "0 30 8,12,19,6-23/3 * * * *"
          enable: true
          argument: jd_cfd&jd_superMarket&jd_jxmc&jd_joy_park&jd_ddo_pk
    - timer: ##特物z #汪汪乐园
        parameters:
          name: superBrand_joypark
          cronExpression: "0 10 9,21 * * * *"
          enable: true
          argument: jd_superBrand&jd_joy_park_task
    - timer: #京豆变动通知 #疯狂的joy #京东排行榜 #领京豆额外奖励 #闪购盲盒 #京小兑 #特物z
        parameters:
          name: beanchange_crazyjoy_rankingList_beanhome_sgmh_jxd
          cronExpression: "0 10 0 * * * *"
          enable: true
          argument: jd_bean_change&jd_crazy_joy&jd_rankingList&jd_bean_home&jd_sgmh&jd_jxd&jd_superBrand
    - timer: #金融养猪 #十元街 #京东快递 #京东赚赚 #点点券 #女装盲盒 #电竞经理 #东东乐园 #柠檬零食街  #燃动夏季领取会员奖励（一次性）
        parameters:
          name: pigPet_syj_kd_jdzz_nzmh_necklace_nzmh_djjl_ddly_lsj
          cronExpression: "0 20 0,7,20 * * * *"
          enable: true
          argument: jd_pigPet&jd_syj&jd_kd&jd_jdzz&jd_necklace&jd_nzmh&&jd_djjl&jd_ddly&jd_lsj&jd_summer_movement_card
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的