version: "3"
services:
  jd_scripts1: #默认
    image: akyakya/jd_scripts
    restart: always
    container_name: jd_scripts1
    tty: true
    volumes:
      - ./logs1:/scripts/logs
    environment:
      - JD_COOKIE=pt_key=AAJfjaNrADAS8ygfgIsOxxxxxxxKpfDaZ2pSBOYTxtPqLK8U1Q;pt_pin=lxxxxxx5;
      - TG_BOT_TOKEN=130xxxx280:AAExxxxxxWP10zNf91WQ
      - TG_USER_ID=12xxxx206
  jd_scripts2: #默认
    image: akyakya/jd_scripts
    restart: always
    container_name: jd_scripts2
    tty: true
    volumes:
      - ./logs2:/scripts/logs
    environment:
      - JD_COOKIE=pt_key=AAJfjaNrADAS8ygfgIsOxxxxxxxKpfDaZ2pSBOYTxtPqLK8U1Q;pt_pin=lxxxxxx5;
      - TG_BOT_TOKEN=130xxxx280:AAExxxxxxWP10zNf91WQ
      - TG_USER_ID=12xxxx206
  jd_scripts4: #自定义追加默认之后
    image: akyakya/jd_scripts
    restart: always
    container_name: jd_scripts4
    tty: true
    volumes:
      - ./logs4:/scripts/logs
      - ./my_crontab_list4.sh:/scripts/docker/my_crontab_list.sh
    environment:
      - JD_COOKIE=pt_key=AAJfjaNrADAS8ygfgIsOxxxxxxxKpfDaZ2pSBOYTxtPqLK8U1Q;pt_pin=lxxxxxx5;
      - TG_BOT_TOKEN=130xxxx280:AAExxxxxxWP10zNf91WQ
      - TG_USER_ID=12xxxx206
      - CUSTOM_LIST_FILE=my_crontab_list.sh
  jd_scripts5: #自定义覆盖默认
    image: akyakya/jd_scripts
    restart: always
    container_name: jd_scripts5
    tty: true
    volumes:
      - ./logs5:/scripts/logs
      - ./my_crontab_list5.sh:/scripts/docker/my_crontab_list.sh
    environment:
      - JD_COOKIE=pt_key=AAJfjaNrADAS8ygfgIsOxxxxxxxKpfDaZ2pSBOYTxtPqLK8U1Q;pt_pin=lxxxxxx5;
      - TG_BOT_TOKEN=130xxxx280:AAExxxxxxWP10zNf91WQ
      - TG_USER_ID=12xxxx206
      - CUSTOM_LIST_FILE=my_crontab_list.sh
      - CUSTOM_LIST_MERGE_TYPE=overwrite
